=== ClustProject/KETIToolMetaManager/metaSchema/metaSchema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"domain": {"type": "string"},
		"sub_domain": {"type": "string"},
		"table_name": {"type": "string"},
		"start_time": {"type": "string"},
		"end_time": {"type": "string"},
		"fields": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"fieldKey": {"type": "string"},
					"fieldType": {"type": "string"}
				},
				"required": [
					"fieldKey", "fieldType"
				]
			}
		},
		"number_of_columns": {
			"type": "integer"
		},
		"location": {
			"type": "object",
			"properties": {
				"lat": {"type": "number"},
				"lng": {"type": "number"},
				"syntax": {"type": "string"}
			}
		},
		"description": {"type": "string"},
		"tag": {
			"type": "array",
			"items": {"type": "string"}
		},
		"frequency": {"type": "string"},
		"column_information": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"column_name": {"type": "string"},
					"analysisResult": {
						"type": "object",
						"properties": {
							"labelBasedResult": {
								"type": "array",
								"items": {
									"type": "object",
									"properties": {
										"analysisName": {"type": "string"},
										"characteristics": {
											"enum": ["mean", "count"]
										},
										"result": {
											"type": "array",
											"items": {
												"type": "object",
												"properties": {
													"labelList": {
														"type": "array",
														"items": {"type": "string"}
													},
													"labelValue": {
														"type": "array",
														"items": {"type": "number"}
													}
												},
												"required": ["labelList", "labelValue"]
											}
										}
									},
									"required": ["analysisName", "characteristics", "result"]
								}
							},
							"levellBasedResult": {
								"type": "array",
								"items": {
									"type": "object",
									"properties": {
										"analysisName": {"type": "string"},
										"characteristics": {
											"enum": ["mean", "count"]
										},
										"result": {
											"type": "array",
											"items": {
												"type": "object",
												"properties": {
													"levelValue": {"type": "integer"},
													"levelName": {"type": "string"}
												},
												"required": ["levelValue", "levelName"]
											}
										}
									},
									"required": ["analysisName", "characteristics", "result"]
								}
							}
						}
					}
				},
				"required": [
					"name"
				]
			}
		}
	},
	"required": [
		"domain", "sub_domain", "table_name"
	]
}

=== ClustProject/KETIToolMetaManager/metaSchema/metaEaxample.json
{
	"domain": "air",
	"sub_domain": "indoor_____",
	"table_name": "ICW0W2000635",
	"start_time": "2020-07-07T16:39:00Z",
	"end_time": "2020-07-08T08:57:00Z",
	"fields": [
		{
			"fieldKey": "in_temp",
			"fieldType": "float"
		}
	],
	"number_of_columns": 20,
	"location": {
		"lat": 35.2080612998422,
		"lng": 129.080749936401,
		"syntax": "____ _____ ___ ___78__ 13-3"
	},
	"description": "This is weather data",
	"tag": [
		"wheather", "indoor", "air", "____"
	],
	"frequency": "0 days 00:01:00",
	"column_information": [
		{
			"name": "in_temp",
			"statistics_result": {
				"labelBasedResult": [
					{
						"name": "statistics",
						"characteristics": "average",
						"result": [
							{
								"label": [
									"count", "mean", "std", "min", "25%", "50%", "75%", "max"
								],
								"value": [
									1, 2, 0, 3, 0.5, 0.2, 2.3, 2.3, 2.3, 3
								]
							}
						]
					}, {
						"name": "feature_label",
						"characteristics": "count",
						"result": [
							{
								"value": 0,
								"name": "____"
							}, {
								"value": 0,
								"name": "__"
							}, {
								"value": 0,
								"name": "__"
							}, {
								"value": 0,
								"name": "__"
							}, {
								"value": 2,
								"name": "__"
							}, {
								"value": 576,
								"name": "__"
							}, {
								"value": 394,
								"name": "____"
							}
						]
					}, {
						"name": "holiday",
						"characteristics": "average",
						"result": [
							{
								"value": 30,
								"name": "notHoliday"
							}, {
								"value": "None",
								"name": "Holiday"
							}
						]
					}, {
						"name": "working_time",
						"characteristics": "average",
						"result": [
							{
								"value": 29,
								"name": "notWorking"
							}, {
								"value": 33,
								"name": "working"
							}
						]
					}, {
						"name": "time_step",
						"characteristics": "average",
						"result": [
							{
								"label": [
									"a", "b", "c"
								],
								"value": [
									0, 3, 50
								]
							}
						]
					}
				]
			}
		}
	]
}
